# Continuous Integration Workflow

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [master]
    types: [opened, synchronized, reopened]
    paths: 
      - "src/**"
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      #Checkout
      - name: Checkout
        uses: actions/checkout@v2
      #Node Setup
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      #Cache dependencies for faster workflow runs
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      #Install with npm
      - name: Install modules
        run: npm ci
        working-directory: $GITHUB_WORKSPACE/src/easify/
      #Run ESLint
      - name: Lint
        run: npm run lint
        working-directory: $GITHUB_WORKSPACE/src/easify/
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      #Checkout
      - name: Checkout
        uses: actions/checkout@v2
      #Node Setup
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      #Cache dependencies for faster workflow runs
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      #Install with npm
      - name: Install modules
        run: npm ci
        working-directory: $GITHUB_WORKSPACE/src/easify/
      #Build and test
      - name: Build
        run: npm run build
        working-directory: $GITHUB_WORKSPACE/src/easify/

